/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Group9d;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.Calendar;
import java.util.GregorianCalendar;
/**
 *
 * @author Nigel Itotia
 */

public class Policelogin extends javax.swing.JFrame {
        Connection conn = null;
        ResultSet rs = null;
        PreparedStatement pst = null;
    /**
     * Creates new form Policelogin
     */
    public Policelogin() {
        
        initComponents();
        conn = Db.java_db();
        currentDate();
              
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/6 - getWidth()/6,size.height/7 - getHeight()/7);
        
    }

    public void currentDate(){
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        lbl_date.setText((month +1)+"/"+day+"/"+year);
        
        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar. HOUR);
        
        lbl_time.setText(hour+":"+(minute)+":"+second);
    }
    
    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        txt_combo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        Loginbttn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        lbl_date = new javax.swing.JMenu();
        lbl_time = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        txt_username.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_username.setPreferredSize(new java.awt.Dimension(156, 26));
        jPanel1.add(txt_username);
        txt_username.setBounds(470, 480, 420, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Please enter your Badge Number and Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 400, 610, 30);

        txt_password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txt_password);
        txt_password.setBounds(466, 575, 430, 40);

        jPanel2.setLayout(null);

        txt_combo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Officers", "Police(O.C)" }));
        jPanel2.add(txt_combo);
        txt_combo.setBounds(570, 660, 180, 26);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group9d/images/zx.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 1370, 770);

        Loginbttn.setText("jButton1");
        Loginbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginbttnActionPerformed(evt);
            }
        });
        jPanel2.add(Loginbttn);
        Loginbttn.setBounds(1000, 670, 330, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1370, 770);

        lbl_date.setText("Date");
        lbl_date.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuBar1.add(lbl_date);

        lbl_time.setText("Time");
        lbl_time.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuBar1.add(lbl_time);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginbttnActionPerformed
//need to fing out why the code is not working or syinching
        String sql = "select * from `users` where BadgeID=? and Password=? and Division = ?";
        try {
            int count = 0;
            
            pst = conn.prepareStatement(sql);
            
            pst.setString(1, txt_username.getText());
            pst.setString(2, txt_password.getText());
            pst.setString(3, txt_combo.getSelectedItem().toString());
            
            rs = pst.executeQuery();
            
            while(rs.next()){
                int ID = rs.getInt(1);
                Emp.ID1 = ID;
                count = count +1;
            }
            String access = (txt_combo.getSelectedItem().toString());
            
            if (access =="Police(O.C)")
            {
                if(count == 1){
                    JOptionPane.showMessageDialog(null, "Welcome Officer");
                    ACwindow j = new ACwindow();
                    j.setVisible(true);
                    this.dispose();
                    java.awt.EventQueue.invokeLater(new Runnable() {
            // these lines force the screen to the foreground and centere it
                    public void run() {
                    j.toFront();
                    j.repaint();
                    j.setLocationRelativeTo(null);
            }
        });
                }
                else{
                    JOptionPane.showMessageDialog(null, "The BadgeID or Password you have entered are wrong!");
                    
                }
                
            }
            else if (access =="Officers")
            {
                if(count == 1){
                    JOptionPane.showMessageDialog(null, "Welcome Officer");
                    Cases j = new Cases();
                    j.setVisible(true);
                    this.dispose();
                    java.awt.EventQueue.invokeLater(new Runnable() {
            // these lines force the screen to the foreground and centere it
                    public void run() {
                    j.toFront();
                    j.repaint();
                    j.setLocationRelativeTo(null);
            }
        });
                }
                else{
                    JOptionPane.showMessageDialog(null, "The BadgeID or Password you have entered are wrong!");
                    
                }
            
        }
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        finally{
            try{
                rs.close();
                pst.close();
            }catch (Exception e){
                
            }
        }
        
        
    }//GEN-LAST:event_LoginbttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Policelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Policelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Policelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Policelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Policelogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Loginbttn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu lbl_date;
    private javax.swing.JMenu lbl_time;
    private javax.swing.JComboBox<String> txt_combo;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
private void systemExit()
    {
        WindowEvent winClosing = new WindowEvent (this, WindowEvent.WINDOW_CLOSING);
    }
}
